/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ingenierias.ucaldas.edu.co;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author daner
 */
public class Registro_de_Expositores extends javax.swing.JFrame {

    /**
     * Creates new form Registro_de_Asistentes
     */
    
    private final ArrayList<Expositor> List;
    
    public Registro_de_Expositores() {
        List = new ArrayList<>();
        initComponents();
        this.setLocationRelativeTo(null);
        Cargar();
        Limpiar();
        
        
        // Dias en los que se llevaran a cabo los eventos
        
        jComboBox_Dia.addItem("Lunes");
        jComboBox_Dia.addItem("Martes");
        jComboBox_Dia.addItem("Miercoles");
        jComboBox_Dia.addItem("jueves");
        jComboBox_Dia.addItem("Viernes");
        jComboBox_Dia.addItem("Sabado");
        jComboBox_Dia.addItem("Domingo");
        
        // Hora en la que van a exponer 
       
        jComboBox_Hora.addItem("8:00am");
        jComboBox_Hora.addItem("9:00am");
        jComboBox_Hora.addItem("10:00am");
        jComboBox_Hora.addItem("11:00am");
        jComboBox_Hora.addItem("2:00pm");
        jComboBox_Hora.addItem("3:00pm");
        jComboBox_Hora.addItem("4:00pm");
        jComboBox_Hora.addItem("5:00pm");
        
        // Salones en los que se van a llevar a cabo los eventos
        
        jComboBox_Salon.addItem("Salón de Ingeniería");
        jComboBox_Salon.addItem("Salón de Artes");
        jComboBox_Salon.addItem("Salón de Humanidades");
        jComboBox_Salon.addItem("Salón de Medicina");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Cedula = new javax.swing.JTextField();
        jTextField_Computadores = new javax.swing.JTextField();
        jTextField_Proyectores = new javax.swing.JTextField();
        jTextField_Tema = new javax.swing.JTextField();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Expositores = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_Hora = new javax.swing.JComboBox<>();
        jComboBox_Dia = new javax.swing.JComboBox<>();
        jComboBox_Salon = new javax.swing.JComboBox<>();
        jButton_Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE EXPOSITORES");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Cedula");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Dia del Evento");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Hora");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad de Computadores");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Tema a exponer");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad de proyectores");

        jTextField_Nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreActionPerformed(evt);
            }
        });
        jTextField_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NombreKeyTyped(evt);
            }
        });

        jTextField_Cedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CedulaKeyTyped(evt);
            }
        });

        jTextField_Computadores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Computadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ComputadoresActionPerformed(evt);
            }
        });
        jTextField_Computadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ComputadoresKeyTyped(evt);
            }
        });

        jTextField_Proyectores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Proyectores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ProyectoresKeyTyped(evt);
            }
        });

        jTextField_Tema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Tema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TemaActionPerformed(evt);
            }
        });

        jButton_Agregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarActionPerformed(evt);
            }
        });

        jButton_Modificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Modificar.setText("Modificar");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Volver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jTable_Expositores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable_Expositores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula ", "Proyectores", "Dia del evento", "Hora", "Tema a exponer", "Computadores", "Salon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Expositores);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Salon");

        jComboBox_Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_HoraActionPerformed(evt);
            }
        });

        jComboBox_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DiaActionPerformed(evt);
            }
        });

        jComboBox_Salon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SalonActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(125, 125, 125))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(82, 82, 82)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Proyectores, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Computadores, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jTextField_Tema, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jComboBox_Hora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Salon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jButton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField_Computadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jTextField_Proyectores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar(){
    jTextField_Nombre.setText("");
    jTextField_Cedula.setText("");
    jTextField_Proyectores.setText("1");
    jTextField_Tema.setText("");
    jTextField_Computadores.setText("1");
    }
    
    private void MostrarPersona(Expositor auxiliar) {
        
            String Matriz [][] = new String [1][8];
        
            Matriz [0][0] = auxiliar.getNombre();
            Matriz [0][1] = auxiliar.getCedula();
            Matriz [0][2] = Integer.toString(auxiliar.getProyector());
            Matriz [0][3] = auxiliar.getDia();
            Matriz [0][4] = auxiliar.getHora();
            Matriz [0][5] = auxiliar.getTema();
            Matriz [0][6] = Integer.toString(auxiliar.getComputador());
            Matriz [0][7] = auxiliar.getSalon();
           
            
                    jTable_Expositores.setModel(new javax.swing.table.DefaultTableModel(
Matriz,
            new String [] {
                "Nombre", "Cedula ", "Proyectores", "Dia del evento", "Hora", "Tema a exponer", "Computadores", "Salon"
            }
        ));
        
     
    }
    
    private void Mostrar_datos(){
        String Matriz [][] = new String [List.size()][8];
        
        Expositor auxiliar;
        
        for (int i = 0; i < List.size(); i++) {
            auxiliar = List.get(i);
            Matriz [i][0] = auxiliar.getNombre();
            Matriz [i][1] = auxiliar.getCedula();
            Matriz [i][2] = Integer.toString(auxiliar.getProyector());
            Matriz [i][3] = auxiliar.getDia();
            Matriz [i][4] = auxiliar.getHora();
            Matriz [i][5] = auxiliar.getTema();
            Matriz [i][6] = Integer.toString(auxiliar.getComputador());
            Matriz [i][7] = auxiliar.getSalon();
                    jTable_Expositores.setModel(new javax.swing.table.DefaultTableModel(
Matriz,
            new String [] {
                "Nombre", "Cedula ", "Proyectores", "Dia del evento", "Hora", "Tema a exponer", "Computadores", "Salon"
            }
        ));
        }
        
        
    }
    
        private void Agragar_a_tabla(){
        
    String Nombre;
    String Cedula;
    int proyector;
    String dia;
    String Hora;
    String Tema;
    int computador;
    String Salon;
        
        try {
            Nombre = jTextField_Nombre.getText();
            Cedula = jTextField_Cedula.getText();
            proyector = Integer.parseInt(jTextField_Proyectores.getText());
            dia = jComboBox_Dia.getSelectedItem().toString();
            Hora = jComboBox_Hora.getSelectedItem().toString();
            Tema = jTextField_Tema.getText();
            computador = Integer.parseInt(jTextField_Computadores.getText());
            Salon = jComboBox_Salon.getSelectedItem().toString();
           
         
            List.add(new Expositor(Nombre, Cedula, proyector, dia, Hora, Tema, computador, Salon));
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Verifica los datos");
        }
        
        Mostrar_datos();
    }
    
    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed

                        boolean bandera = false;
        
            for(int i=0; i<List.size(); i++){
                if(jComboBox_Dia.getSelectedItem().toString().equals(List.get(i).getDia())
                        && jComboBox_Hora.getSelectedItem().toString().equals(List.get(i).getHora())
                        && jComboBox_Salon.getSelectedItem().toString().equals(List.get(i).getSalon())){
                    bandera = true;
                   }                   
          }
            
            if(bandera == false){
                Agragar_a_tabla ();

            }else{
             JOptionPane.showMessageDialog(null,"El puesto ya se encuentra ocupado, selecciona otro");
            }
        Limpiar ();
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        
        Guardar();
        Menu Me = new Menu ();
        Me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jTextField_ComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ComputadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ComputadoresActionPerformed

    private void jComboBox_HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_HoraActionPerformed

    private void jComboBox_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DiaActionPerformed

    private void jComboBox_SalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SalonActionPerformed

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        int fila; 
        String Cedula;
        Expositor auxiliar;
        
        try {
            fila = jTable_Expositores.getSelectedRow();
            auxiliar = List.get(fila);
            Cedula = JOptionPane.showInputDialog("Ingresa el nuevo numero de cedula");
            auxiliar.setCedula(Cedula);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }
        Mostrar_datos();
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    private void jTextField_TemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TemaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                String botones [] = {"Si","No"};
        int ventana = JOptionPane.showOptionDialog(null,"Desea guardar la información", "salir", 0, 0, null, botones, null);
        
        if (ventana == 0){
            Guardar();
        
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
              
          if (!jTextField_Cedula.getText().isEmpty()){
          Expositor auxiliar = null;
          String Buscar = jTextField_Cedula.getText();
          
          for (int i = 0; i < List.size(); i++) {
              
              auxiliar = List.get(i);
              
              if (auxiliar.getCedula().equals(Buscar)) {
                  MostrarPersona(auxiliar);
                  
              }
          }
          
      }
      else {
          JOptionPane.showMessageDialog(null, "Por favor ingrese la cedula");
      }
    
        
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
                        int fila;
        
        try {
            
            fila = jTable_Expositores.getSelectedRow();
            List.remove(fila);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Por favor seleccione la fila que va eliminar");
        }
        
        Mostrar_datos();
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
       Mostrar_datos();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jTextField_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreKeyTyped
                Character Nombre = evt.getKeyChar();
        
        if (!Character.isLetter(Nombre) && Nombre != KeyEvent.VK_SPACE){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NombreKeyTyped

    private void jTextField_CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CedulaKeyTyped
        
        Character Cedula = evt.getKeyChar();
        
        if (!Character.isDigit(Cedula)){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CedulaKeyTyped

    private void jTextField_ProyectoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ProyectoresKeyTyped
        
        Character Proyectores = evt.getKeyChar();
        if (!Character.isDigit(Proyectores)){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ProyectoresKeyTyped

    private void jTextField_ComputadoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ComputadoresKeyTyped
        
        Character Computadores = evt.getKeyChar();
        if (!Character.isDigit(Computadores)){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ComputadoresKeyTyped

        // Esta es una función para guardar los datos de los asistentes
    private void Guardar (){
    
        File file = new File ("Expositor.txt");
        PrintWriter Escribe;
        if (!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) {
            }
        }
        
        try {
            Expositor auxiliar;
            Escribe = new PrintWriter(file,"utf-8");
            
            for (int i = 0; i < List.size(); i++) {
                auxiliar = List.get(i);
                auxiliar.Guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
    
    // Con esta función se reflrezca los datos desde un txt que se genera automaticamente al guardarlos.
    public void Cargar(){
    
        File Archivo = new File ("Expositor.txt");
        FileReader Leer;
        BufferedReader Almacen;
        
        Expositor persona, auxiliar = new Expositor();
        
        try {
            
            Leer = new FileReader(Archivo);
            Almacen = new BufferedReader(Leer);
            persona = auxiliar.Cargar(Almacen);
            
            while (persona != null){
            
                List.add(persona);
                persona = auxiliar.Cargar(Almacen);
            }
         Almacen.close();
         Leer.close();
            
        } catch (Exception e) {
        }
        Mostrar_datos();
    }
    
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Expositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Expositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Expositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Expositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registro_de_Expositores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JComboBox<String> jComboBox_Dia;
    private javax.swing.JComboBox<String> jComboBox_Hora;
    private javax.swing.JComboBox<String> jComboBox_Salon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Expositores;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Computadores;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Proyectores;
    private javax.swing.JTextField jTextField_Tema;
    // End of variables declaration//GEN-END:variables

}
