/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ingenierias.ucaldas.edu.co;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author daner
 */
public class Registro_de_Asistentes extends javax.swing.JFrame {

    /**
     * Creates new form Registro_de_Asistentes
     */
    
    private final ArrayList<Asistente> List;
    
    public Registro_de_Asistentes() {
        List = new ArrayList<>();
        initComponents();
        Cargar();
        this.setLocationRelativeTo(null);
        
        
        jComboBox_Dia.addItem("Lunes");
        jComboBox_Dia.addItem("Martes");
        jComboBox_Dia.addItem("Miercoles");
        jComboBox_Dia.addItem("jueves");
        jComboBox_Dia.addItem("Viernes");
        jComboBox_Dia.addItem("Sabado");
        jComboBox_Dia.addItem("Domingo");
        
        llenar_Puestos();
        
    
    

    }
    
    
    public void llenar_Puestos (){
    
        for (int i = 1; i <= 384; i++) {
            
            jComboBox_Puestos.addItem(String.valueOf(i));
            
        }
    }   
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Cedula = new javax.swing.JTextField();
        jTextField_Edad = new javax.swing.JTextField();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Asistentes = new javax.swing.JTable();
        jComboBox_Dia = new javax.swing.JComboBox<>();
        jButton_Escenario = new javax.swing.JButton();
        jComboBox_Puestos = new javax.swing.JComboBox<>();
        jButton_Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE ASISTENTES");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Cedula");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("N° de Puesto");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Dia del Evento");

        jTextField_Nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NombreKeyTyped(evt);
            }
        });

        jTextField_Cedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CedulaKeyTyped(evt);
            }
        });

        jTextField_Edad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EdadKeyTyped(evt);
            }
        });

        jButton_Agregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarActionPerformed(evt);
            }
        });

        jButton_Modificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Modificar.setText("Modificar");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Volver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jTable_Asistentes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable_Asistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula ", "Edad", "N° de Puesto", "Dia del Evento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Asistentes);

        jComboBox_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DiaActionPerformed(evt);
            }
        });

        jButton_Escenario.setText("Escenario");
        jButton_Escenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EscenarioActionPerformed(evt);
            }
        });

        jComboBox_Puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PuestosActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jButton_Escenario))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel1)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Escenario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Puestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar(){
    jTextField_Nombre.setText("");
    jTextField_Cedula.setText("");
    jTextField_Edad.setText("");
    
    }
    
    private void MostrarPersona(Asistente auxiliar) {
        
            String Matriz [][] = new String [1][5];
        
            Matriz [0][0] = auxiliar.getNombre();
            Matriz [0][1] = auxiliar.getCedula();
            Matriz [0][2] = Integer.toString(auxiliar.getedad());
            Matriz [0][3] = auxiliar.getsilla();
            Matriz [0][4] = auxiliar.getDia();
           
            
                    jTable_Asistentes.setModel(new javax.swing.table.DefaultTableModel(
Matriz,
            new String [] {
                "Nombre", "Cedula ", "Edad", "N° de Puesto", "Dia del Evento"
            }
        ));
        
     
    }
    
    // Esta es una función que muestra datos en una matriz bidimencional que posteriormente se reflejan en la tabla
    private void Mostrar_datos(){
        String Matriz [][] = new String [List.size()][5];
        
        Asistente auxiliar;
        
        for (int i = 0; i < List.size(); i++) {
            auxiliar = List.get(i);
            Matriz [i][0] = auxiliar.getNombre();
            Matriz [i][1] = auxiliar.getCedula();
            Matriz [i][2] = Integer.toString(auxiliar.getedad());
            Matriz [i][3] = auxiliar.getsilla();
            Matriz [i][4] = auxiliar.getDia();
            
                    jTable_Asistentes.setModel(new javax.swing.table.DefaultTableModel(
Matriz,
            new String [] {
                "Nombre", "Cedula ", "Edad", "N° de Puesto", "Dia del Evento"
            }
        ));
        }
        
        
    }
    
    private void Agragar_a_tabla(){
        
        String Nombre;
        int edad;
        String silla;
        String Cedula;
        String Dia;
        
        
 try {

         Nombre = jTextField_Nombre.getText();
         Cedula = jTextField_Cedula.getText();
         edad = Integer.parseInt(jTextField_Edad.getText());
         silla = jComboBox_Puestos.getSelectedItem().toString();
         Dia = jComboBox_Dia.getSelectedItem().toString();
         
         List.add(new Asistente(Nombre, Cedula, edad, silla, Dia));
         
} catch (Exception e) {
     JOptionPane.showMessageDialog(null,"Verifica los datos");
        }
      
       Mostrar_datos();
        
    }
    
    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed

                boolean bandera = false;
        
            for(int i=0; i<List.size(); i++){
                if(jComboBox_Puestos.getSelectedItem().toString().equals(List.get(i).getsilla())
                        && jComboBox_Dia.getSelectedItem().toString().equals(List.get(i).getDia())){
                    bandera = true;
                   }                   
          }
            
            if(bandera == false){
                Agragar_a_tabla ();

            }else{
             JOptionPane.showMessageDialog(null,"El puesto ya se encuentra ocupado, selecciona otro");
            }
            
        Limpiar ();
    
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
     Guardar();
        Menu Me = new Menu ();
        Me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jComboBox_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DiaActionPerformed

    }//GEN-LAST:event_jComboBox_DiaActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        
        int fila;
        
        try {
            
            fila = jTable_Asistentes.getSelectedRow();
            List.remove(fila);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Por favor seleccione la fila que va eliminar");
        }
        
        Mostrar_datos();
    }//GEN-LAST:event_jButton_EliminarActionPerformed

        
    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        int fila; 
        String Cedula;
        Asistente auxiliar;
                
        try {
            fila = jTable_Asistentes.getSelectedRow();
            auxiliar = List.get(fila);
            Cedula = JOptionPane.showInputDialog("Ingresa el nuevo numero de cedula");
            auxiliar.setCedula(Cedula);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }
        Mostrar_datos();
        
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    
    // Esta es una función para guardar los datos de los asistentes
    private void Guardar (){
    
        File file = new File ("Asistentes.txt");
        PrintWriter Escribe;
        if (!file.exists()){
            try {
                file.createNewFile();
            } catch (Exception e) {
            }
        }
        
        try {
            Asistente auxiliar;
            Escribe = new PrintWriter(file,"utf-8");
            
            for (int i = 0; i < List.size(); i++) {
                auxiliar = List.get(i);
                auxiliar.Guardar(Escribe);
            }
            Escribe.close();
        } catch (Exception e) {
        }
    }
    
    
    // Con esta función se reflrezca los datos desde un txt que se genera automaticamente al guardarlos.
    public void Cargar(){
        
    File Archivo = new File ("Asistentes.txt");
        FileReader Leer;
        BufferedReader Almacen;
        
        Asistente persona, auxiliar = new Asistente();
        
        try {
            
            Leer = new FileReader(Archivo);
            Almacen = new BufferedReader(Leer);
            persona = auxiliar.Cargar(Almacen);
            
            while (persona != null){
            
                List.add(persona);
                persona = auxiliar.Cargar(Almacen);
            }
         Almacen.close();
         Leer.close();
            
        } catch (Exception e) {
        }
        Mostrar_datos();
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String botones [] = {"Si","No"};
        int ventana = JOptionPane.showOptionDialog(null,"Desea guardar la información", "salir", 0, 0, null, botones, null);
        
        if (ventana == 0){
            Guardar();
        
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton_EscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EscenarioActionPerformed
 
                 JOptionPane.showMessageDialog(null,"Descripción grafica del escenario");
                 Escenario_Asistentes abrirescenario = new Escenario_Asistentes();
                 abrirescenario.setVisible(true);
                 this.dispose();
        
    }//GEN-LAST:event_jButton_EscenarioActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
          if (!jTextField_Cedula.getText().isEmpty()){
          Asistente auxiliar = null;
          String Buscar = jTextField_Cedula.getText();
          
          for (int i = 0; i < List.size(); i++) {
              
              auxiliar = List.get(i);
              
              if (auxiliar.getCedula().equals(Buscar)) {
                  MostrarPersona(auxiliar);
                  
              }
          }
          
      }
      else {
          JOptionPane.showMessageDialog(null, "Por favor ingrese la cedula");
      }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jComboBox_PuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PuestosActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        Mostrar_datos(); 
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jTextField_CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CedulaKeyTyped
       
        Character Cedula = evt.getKeyChar();
        
        if (!Character.isDigit(Cedula)){
            
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextField_CedulaKeyTyped

    private void jTextField_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreKeyTyped
        
        Character Nombre = evt.getKeyChar();
        
        if (!Character.isLetter(Nombre) && Nombre != KeyEvent.VK_SPACE){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NombreKeyTyped

    private void jTextField_EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EdadKeyTyped
        
        Character Edad = evt.getKeyChar();
        
        if (!Character.isDigit(Edad)){
            
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_EdadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Asistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Asistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Asistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Asistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_de_Asistentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Escenario;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JComboBox<String> jComboBox_Dia;
    private javax.swing.JComboBox<String> jComboBox_Puestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Asistentes;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Edad;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables




}
